### ISSUE TITLE
Unmapped columns panic

### ISSUE THREAD

**Issue by jbowens** [square/squalor#11]
Should this really be a panic? https://github.com/square/squalor/blob/70a85e2d584e57cb6433bab1a80e7178802289ac/reflect.go#L96

Deploys and migrations don't always occur simultaneously, and even if they do, this can make rolling back a pain.

**Comment by petermattis** [comment]
I could be convinced this shouldn't be a panic. This code was inspired by https://github.com/jmoiron/sqlx/blob/master/reflectx/reflect.go#L127 which does not panic. I think I had a rationale for panicing when I wrote this, but can't recall off-hand what it was.

**Comment by jbowens** [comment]
Fixed in #13
