### ISSUE TITLE
Add GetModel to Executor interface

### ISSUE THREAD

**Issue by bradseiler** [square/squalor#33]
For code cleanliness, I often find that I don't want to pass both a *DB and a *Tx around my logic flow, so I pass whichever I am using as a Executor. Whenever I need a model, though, I need to get it from the *DB and either pass it with the Executor, or pass the *DB around with the Executor. I propose to add the GetModel method to the Executor interface, and use the *DB internal to a *Tx to implement it.

**Comment by mikekono** [comment]
I've run into the same thing. Sounds good to me.
