### ISSUE TITLE
Optimistic locking support

### ISSUE THREAD

**Issue by pascallouisperez** [square/squalor#44]
It would be nice to have a way to mark a field on a struct as the version of an object, and have `Update`, `Upsert`, etc. respect it.

For instance

    type User struct {
      ID      int64
      Version int `db:",optlock"`
      Name    string
    }

And upon an `Update`, the query would be

    UPDATE ..., set version = version + 1 WHERE id= ? and version = ?

fail if no rows were changed, and upon success, update the Version field in the struct in-memory.

Happy to implement it btw, as I need this in a project ;)

cc @bradseiler

**Comment by bradseiler** [comment]
@pascallouisperez That sounds fine. Happy to review the PR.

**Comment by pascallouisperez** [comment]
Super. Will send hopefully early next week.
